### ISSUE TITLE
Incorrect read

### ISSUE THREAD

**Issue by Leemurus** [idlesign/pysyge#14] opened 2020-08-05 16:19 UTC
24.231.175.176 - error in 2020.07.31 building

**Comment by idlesign** [comment] 2020-08-06 00:21
If this belong to #13, please close the issue and update the description of the related.
If not, please provide full erro details.

**Comment by Leemurus** [comment] 2020-08-06 10:39
Traceback (most recent call last):
  File "/home/leemurus/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/201.8743.11/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/leemurus/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/201.8743.11/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/leemurus/Programming/Python/DatabaseCompare/dat_to_csv_old.py", line 331, in <module>
    get_location()
  File "/home/leemurus/Programming/Python/DatabaseCompare/dat_to_csv_old.py", line 327, in get_location
    pprint(db._parse_location(db.get_location(ip), detailed=True))
  File "/home/leemurus/Programming/Python/DatabaseCompare/databases/pysyge.py", line 309, in _parse_location
    city = self._read_data_chunk(self._TYPE_CITY, start_pos, self._max_city)
  File "/home/leemurus/Programming/Python/DatabaseCompare/databases/pysyge.py", line 292, in _read_data_chunk
    return self._parse_pack(self._pack[data_type], raw)
  File "/home/leemurus/Programming/Python/DatabaseCompare/databases/pysyge.py", line 413, in _parse_pack
    val_real = val_real()
  File "/home/leemurus/Programming/Python/DatabaseCompare/databases/pysyge.py", line 384, in <lambda>
    'N': lambda: unpack('i', val)[0] / pow(10, int(chr_(chunk_type[1]))),
struct.error: unpack requires a buffer of 4 bytes

**Comment by idlesign** [comment] 2020-08-06 12:03
Thank you.
Will fix when have time, or pull request (fix + test) is welcome if you wish.

**Comment by idlesign** [comment] 2020-08-30 01:53
Unable to reproduce for 24.231.175.176 (see linked quirk test).
Please provide a proper example and reopen if required.

**Closed by idlesign** 2020-08-30 01:53 UTC
Labels: bug, invalid
